apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-volume
spec:
  capacity:
    storage: 10Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  storageClassName: slow
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  nfs:
    server: alexandria.local # Please change this to your NFS server
    path: /tank/kubestore/rabbit # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-nfs
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 10Gi # volume size requested
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      volumes:
        - name: rabbit-nfs
          persistentVolumeClaim:
            claimName: rabbit-nfs
      containers:
        - name: rabbit
          image: rabbitmq:management
          ports:
            - containerPort: 5671
            - containerPort: 15672
          volumeMounts:
            - name: rabbit-nfs
              mountPath: /var/lib/rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      protocol: TCP
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 15672
      protocol: TCP
  selector:
    app: rabbitmq
